RA-13 проблема с методом готовки
Slavikus1/RecipesApp pull request #11
Opened 2024-12-21 11:56 UTC by Slavikus1

2024-12-21 19:18 UTC, Churickoid requested changes

2024-12-21 19:18 UTC, Churickoid commented on app/src/main/java/ru/aliohin/recipesapp/MethodAdapter.kt
> +        holder.methodTextView.text = method
Не хватает нумерации как в дизайне из фигмы

2024-12-21 19:18 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            app:layoutManager="androidx.recyclerview.widget.LinearLayoutManager" />
Давай добавим tools, чтоб на макете отображался список

2024-12-21 19:18 UTC, Churickoid commented on app/src/main/res/layout/item_method.xml
> +    android:layout_height="match_parent">
У тебя айтем занимает куча места, перед отправкой надо тестить как выглядит итоговое приложение

2024-12-21 19:18 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_width="match_parent"
Не хватает заднего фона со скругленными углами

2024-12-23 07:42 UTC, Churickoid approved these changes
Молодец, по заданию всё верно! Поправь в следующем ПР комменты связанные с дизайном

2024-12-23 07:42 UTC, Churickoid commented on app/src/main/java/ru/aliohin/recipesapp/RecipeFragment.kt
> +        dividerItemDecoration.dividerColor = Color.WHITE
Цвет divider не соответсвует макетному

2024-12-23 07:42 UTC, Churickoid commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content"
На макете первый и последний элемент занимают больше места. Этого можно добиться, добавим вертикальный padding для самого ресайклера

2024-12-25 16:30 UTC, Slavikus1 commented on app/src/main/res/layout/fragment_recipe.xml
> +            android:layout_height="wrap_content"
Не могу определить на макете какой dp установить верт. паддингу, не вижу

2024-12-25 16:31 UTC, merged