RA-04 добавил фрагмент
Slavikus1/RecipesApp pull request #2
Opened 2024-11-08 14:05 UTC by Slavikus1

2024-11-08 22:06 UTC, Churickoid requested changes

2024-11-08 22:06 UTC, aGroupoid commented on app/src/main/res/layout/fragment_categories_list.xml
> +        android:text="@string/hello_blank_fragment" />
Это тестовая строка, её в ресурсы смысла выносить нету

2024-11-08 22:06 UTC, aGroupoid commented on app/src/main/java/ru/aliohin/recipesapp/MainActivity.kt
> +            fragmentTransaction.commit()
Ты используешь Java метод add из класса FragmentTransaction.java (посмотри его декларацию). Документация же предлагает импользовать Kotlin extension функцию add() из класса FragmentTransaction.kt. 

Именно для импорта метода add нужно было имплементировать библиотеку fragment-ktx. Экстеншн подразумевает принудительное указание типа, а второй параметр с созданием экземпляра фрагмента уже не нужен.

И предлагаю использовать более короткую и свежую форму с применением commit {} – (пример в документации). То есть вся магия должна происходить в одной лямбде.

2024-11-08 22:06 UTC, Churickoid commented on app/src/main/java/ru/aliohin/recipesapp/MainActivity.kt
> +        if (binding.mainContainer != null){
Это условие всегда true, тебе подсказывает студия

2024-11-09 18:56 UTC, Churickoid approved these changes
Апрувлю, молодец. Поправь коммент в следующем ПР

2024-11-09 18:56 UTC, Churickoid commented on app/src/main/java/ru/aliohin/recipesapp/MainActivity.kt
> +            add(R.id.mainContainer, CategoriesListFragment())
Текущий подход при добавлении Джававский, я писал выше. Нужно импортировать из котлин либы метод add и использвать дженерик `< CategoriesListFragment >`

2024-11-09 19:29 UTC, Slavikus1 commented on app/src/main/java/ru/aliohin/recipesapp/MainActivity.kt
> +            add(R.id.mainContainer, CategoriesListFragment())
> котлин либы

сори что не сразу дохожу. У меня он при дженерике ошибкой вставал, потом я догадался, что можно навести на ошибку и имплементировать класс

2024-11-09 19:29 UTC, merged