RA-07 базовая верстка списка категорий
Slavikus1/RecipesApp pull request #5
Opened 2024-11-14 21:45 UTC by Slavikus1

2024-11-15 17:31 UTC, Churickoid commented
Глянь как выглядит на ширком макете фрагмент. Где-то косяк с match_parent и wrap_content по ширине, надо поправить
![image](https://github.com/user-attachments/assets/f4855172-add1-4d19-adf1-072501506b23)

2024-11-15 17:55 UTC, Churickoid requested changes

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            tools:text="BURGERS" />
Текст вне зависимости от надписи капсом должен показывать заглавные буквы. Лучше в отдельный стиль вынести

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/fragment_categories_list.xml
> +        android:layout_height="224dp"
Все эти параметры не забывай выносить в dimens, по аналогии с текстом и цветами

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/fragment_categories_list.xml
> +            android:layout_height="44dp"
Текст всегда делаем по wrap_content. В настройках системы можно менять размер шрифта, в текущий реализации он будет обрезаться по длине

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/fragment_categories_list.xml
> +        android:layout_marginTop="32dp">
В ресурсы dimens

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/fragment_categories_list.xml
> +            android:padding="10dp"
В ресурсы dimens

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_width="156dp"
Ширина картинки по родителю

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +        android:layout_width="156dp"
Ширина Layout тоже по родителю, в задании вроде прописано, чтоб экран по длине был адаптивным

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +        android:paddingBottom="10dp">
Вынести в ресурсы

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_marginStart="8dp"
В ресурсы

2024-11-15 17:55 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="wrap_content"
Не хватает еще цвета и шрифта

2024-11-16 09:48 UTC, Slavikus1 commented on app/src/main/res/layout/fragment_categories_list.xml
> +            android:layout_height="44dp"
Понял. Спасибо!

2024-11-16 17:16 UTC, Churickoid approved these changes
Всё верно сделал, молодец!

2024-11-16 17:16 UTC, Churickoid commented on app/src/main/res/layout/item_category.xml
> +            android:layout_height="130dp"
Это тоже вынести в ресурсы нужно, как и все такие значения. По аналогии с цветами и строками в файлаз colors и strings

2024-11-16 19:32 UTC, merged